// render-css.js — convert elements to CSS text and HTML text (shared by preview & export).
import { slugify, escapeHtml } from "./util.js";

// CSS props allowed to be emitted into a rule (everything else like geometry is handled separately)
const WHITELIST = new Set([
  "display", "width", "height", "flex-direction", "flex-wrap", "align-items",
  "justify-content", "gap", "font-family", "font-size", "font-weight", "line-height",
  "letter-spacing", "text-align", "text-decoration", "color", "background-color",
  "background-image", "background-size", "background-position", "border-width",
  "border-style", "border-color", "border-radius", "box-shadow", "opacity",
  "transform", "transition", "object-fit", "overflow", "cursor", "margin", "padding",
]);

// values that are effectively "empty" and should be omitted to keep output clean
const EMPTY = new Set(["0", "0px", "0px 0px", "none", "transparent", "inherit", ""]);

function num(v) {
  const n = parseFloat(v);
  return Number.isFinite(n) ? n : 0;
}
function isEmpt(v) {
  if (v == null) return true;
  const s = String(v).trim();
  return EMPTY.has(s) || s === "";
}
function isImgUrl(v) {
  if (!v) return false;
  return /^(https?:)?\/\//i.test(v) || /^data:/i.test(v) || /^blob:/i.test(v);
}

// Compute a readable, unique class name per element.
export function computeClassMap(elements) {
  const used = new Map(); // slug -> count
  const map = new Map();  // id -> class
  for (const el of elements) {
    let base = slugify(el.name);
    let cls = base;
    const n = used.get(base) || 0;
    if (n > 0) cls = `${base}-${n + 1}`;
    used.set(base, n + 1);
    const final = ensureUnique(map, cls);
    map.set(el.id, `.${final}`);
  }
  return map;
}
function ensureUnique(map, cls) {
  let c = cls;
  let i = 2;
  const vals = new Set(map.values());
  while (vals.has(`.${c}`)) { c = `${cls}-${i++}`; }
  return c;
}

export function propToDecls(el, includeGeometry = true, relPos = null) {
  const decls = [];
  if (includeGeometry) {
    decls.push(`position:absolute;`);
    decls.push(`left:${num(relPos ? relPos.x : el.x)}px;`);
    decls.push(`top:${num(relPos ? relPos.y : el.y)}px;`);
    decls.push(`width:${num(el.width)}px;`);
    decls.push(`height:${num(el.height)}px;`);
  }
  for (const [k, v] of Object.entries(el.props || {})) {
    if (!WHITELIST.has(k)) continue;
    if (isEmpt(v)) continue;
    // skip geometry keys already emitted above when including geometry
    if (includeGeometry && (k === "width" || k === "height")) continue;
    decls.push(`${k}:${String(v).trim()};`);
  }
  return decls;
}

// Coords map: id -> {x,y}. Elements use absolute canvas coords; children get
// positions relative to their containing parent on export via relPos.
export const EMPTY_CTX = { abs: new Map(), parent: new Map() };

export function buildFuncContext(elements) {
  const ctx = { abs: new Map(), parent: new Map() };
  for (const el of elements) {
    ctx.parent.set(el.id, el.parentId || null);
    ctx.abs.set(el.id, { x: el.x, y: el.y });
  }
  return ctx;
}

export function elementRule(el, className, ctx) {
  let relPos = null;
  if (el.parentId && ctx.abs) {
    const p = ctx.abs.get(el.parentId);
    if (p) relPos = { x: el.x - p.x, y: el.y - p.y };
  }
  const decls = propToDecls(el, true, relPos);
  const body = decls.map(d => "  " + d).join("\n");
  return `/* ${el.name} */\n${className} {\n${body}\n}`;
}

export function buildCssText(elements, opts = {}) {
  const classMap = opts.classMap || computeClassMap(elements);
  const ctx = opts.ctx || buildFuncContext(elements);
  const W = opts.pageWidth, H = opts.pageHeight;
  const pageClass = opts.pageClass || ".webfacer-page";
  const lines = [];
  lines.push(`/* Generated by WebFacer */`);
  lines.push(`body { margin: 0; }`);
  if (W && H) {
    lines.push(`${pageClass} {\n  position: relative;\n  width: ${W}px;\n  height: ${H}px;\n}`);
  } else {
    lines.push(`${pageClass} {\n  position: relative;\n}`);
  }
  lines.push("");
  for (const el of elements) {
    lines.push(elementRule(el, classMap.get(el.id), ctx));
    lines.push("");
    const clips = (el.anims || []).filter(a => (a.tracks || []).length);
    if (clips.length) {
      for (const a of clips) lines.push(buildKeyframes(el, a));
      const animList = clips.map(a => `kf-${el.id}-${a.id} ${+a.duration || 300}ms ${+(a.start || 0)}ms both`);
      lines.push(`.${classMap.get(el.id).replace(/^\./, "")}.wf-play { animation: ${animList.join(", ")}; }`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

function buildKeyframes(el, clip) {
  const name = "kf-" + el.id + "-" + clip.id;
  const lines = [`@keyframes ${name} {`];
  for (const track of (clip.tracks || [])) {
    const kfs = (track.keyframes || []).slice().sort((a, b) => (a.t || 0) - (b.t || 0));
    for (const k of kfs) {
      lines.push(`  ${Math.round((k.t || 0) * 100)}% { ${track.prop}: ${k.value}; animation-timing-function: ${k.ease || "ease"}; }`);
    }
  }
  lines.push("}");
  return lines.join("\n");
}

function buildClickScript(logic, classMap) {
  if (!logic || !logic.length) return "";
  const pairs = logic.map(l => {
    const t = classMap.get(l.triggerId), g = classMap.get(l.targetId);
    if (!t || !g) return null;
    return { trigger: t.replace(/^\./, ""), target: g.replace(/^\./, "") };
  }).filter(Boolean);
  if (!pairs.length) return "";
  const body = pairs.map(p =>
    `document.querySelectorAll('.${p.trigger}').forEach(function(el){ el.addEventListener('click', function(){ var t=document.querySelector('.${p.target}'); if(!t) return; t.classList.remove('wf-play'); void t.offsetWidth; t.classList.add('wf-play'); t.addEventListener('animationend', function h(){ t.classList.remove('wf-play'); t.removeEventListener('animationend', h); }); }); });`
  ).join("\n");
  return `<script>\n(function(){\n${body}\n})();\n</script>`;
}

function elementTag(el) {
  switch (el.type) {
    case "button": return "button";
    case "link": return "a";
    case "input": return "input";
    case "image": return "img";
    case "divider": return "hr";
    case "heading": return "h2";
    case "emoji": return "div";
    default: return "div";
  }
}

export function buildHtmlText(elements, opts = {}) {
  const classMap = opts.classMap || computeClassMap(elements);
  const byParent = new Map();
  for (const el of elements) {
    const key = el.parentId || "__root__";
    if (!byParent.has(key)) byParent.set(key, []);
    byParent.get(key).push(el);
  }
  const roots = byParent.get("__root__") || [];
  const docTitle = opts.title || "WebFacer 设计";

  function render(el, depth) {
    const tag = elementTag(el);
    const cls = (classMap.get(el.id) || "").replace(/^\./, "");
    const pad = "  ".repeat(depth);
    const children = byParent.get(el.id) || [];
    const kids = children.map(c => render(c, depth + 1)).join("\n");
    let open = "";
    let selfClose = false;

    if (tag === "img") {
      if (isImgUrl(el.content)) {
        open = `<img class="${cls}" src="${escapeHtml(el.content)}" alt="">`;
      } else {
        open = `<div class="${cls}" role="img" aria-label="${escapeHtml(el.name || "image")}"></div>`;
      }
      selfClose = true;
    } else if (tag === "input") {
      open = `<input class="${cls}" type="text" placeholder="${escapeHtml(el.content || "")}">`;
      selfClose = true;
    } else if (tag === "hr") {
      open = `<hr class="${cls}">`;
      selfClose = true;
    } else if (tag === "button") {
      open = `<${tag} class="${cls}">${escapeHtml(el.content || "")}</${tag}>`;
      selfClose = true;
    } else {
      const inner = escapeHtml(el.content || "");
      if (inner && children.length) {
        open = `<${tag} class="${cls}">${inner}\n${kids}`;
      } else if (inner) {
        open = `<${tag} class="${cls}">${inner}</${tag}>`;
        selfClose = true;
      } else {
        open = `<${tag} class="${cls}">\n${kids}`;
      }
    }

    if (selfClose) return pad + open;
    return pad + open + `\n${pad}</${tag}>`;
  }

  const body = roots.map(el => render(el, 1)).join("\n");
  const clickScript = buildClickScript(opts.logic || [], classMap);
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(docTitle)}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<main class="webfacer-page">
${body}
</main>
${clickScript}
</body>
</html>`;
}
