// build.mjs — bundle the ES modules into ONE classic script (js/bundle.js).
// Goal: the app must work when opened directly over file:// (Chrome blocks
// `import` / ES modules from file:// via CORS). A single non-module script
// loads fine everywhere. Each source module is wrapped in an IIFE and shares a
// global `window.WF` namespace; `import { a } from "./x.js"` becomes
// `const { a } = WF;` and `export const a` becomes `WF.a = a;`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const MODULES = [
  "js/util.js",
  "js/components.js",
  "js/state.js",
  "js/render-css.js",
  "js/canvas.js",
  "js/left-panel.js",
  "js/inspector.js",
  "js/code-preview.js",
  "js/exporter.js",
  "js/ribbon.js",
  "js/animation.js",
  "js/app.js",
];

// Strip import/export and collect exported names.
export function transform(src) {
  const names = [];
  let code = src;

  // import { a, b as c } from "..."  ->  const { a, b: c } = WF;
  code = code.replace(/^import\s*\{([^}]*)\}\s*from\s*["'][^"']+["'];?\s*$/gm, (m, ns) => `const { ${ns.trim()} } = WF;`);
  // import * as NS from "..." (unused in this codebase, handled defensively)
  code = code.replace(/^import\s*\*\s*as\s+(\w+)\s*from\s*["'][^"']+["'];?\s*$/gm, (m, n) => `const ${n} = WF;`);
  // import "..." side-effect (unused here)
  code = code.replace(/^import\s*["'][^"']+["'];?\s*$/gm, (m) => "");

  // export const/let/var NAME  ->  const/let/var NAME  (record NAME)
  code = code.replace(/^export\s+(const|let|var)\s+([A-Za-z_$][\w$]*)/gm, (m, kw, name) => {
    names.push(name);
    return `${kw} ${name}`;
  });
  // export function/class NAME -> function/class NAME
  code = code.replace(/^export\s+(function|class)\s+([A-Za-z_$][\w$]*)/gm, (m, kw, name) => {
    names.push(name);
    return `${kw} ${name}`;
  });
  // export default ... (unused here)
  code = code.replace(/^export\s+default\b/gm, () => "");

  return { code, names };
}

function buildCore() {
  const parts = [];
  for (const rel of MODULES) {
    const src = readFileSync(join(root, rel), "utf8");
    const { code, names } = transform(src);
    const pushes = names.map(n => `WF.${n} = ${n};`).join("\n");
    parts.push(`// ---- ${rel} ----\n(function(){\n'use strict';\n${code}\n${pushes}\n})();`);
  }
  return parts.join("\n\n");
}

export function buildBundle() {
  const core = buildCore();
  const banner = "/* WebFacer bundle (generated by build.mjs — do not hand-edit) */\nvar WF = window.WF = window.WF || {};\n";
  return banner + "\n" + core + "\n";
}

const out = join(root, "js", "bundle.js");
writeFileSync(out, buildBundle(), "utf8");
console.log(`wrote ${out} (${MODULES.length} modules)`);
