// build.mjs — bundle the ES modules into ONE classic script (js/bundle.js).
// Goal: the app must work when opened directly over file:// (Chrome blocks
// `import` / ES modules from file:// via CORS). A single non-module script
// loads fine everywhere. Each source module is wrapped in an IIFE and shares a
// global `window.WF` namespace; `import { a } from "./x.js"` becomes
// `const { a } = WF;` and `export const a` becomes `WF.a = a;`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const MODULES = [
  "js/util.js",
  "js/components.js",
  "js/state.js",
  "js/render-css.js",
  "js/canvas.js",
  "js/left-panel.js",
  "js/inspector.js",
  "js/code-preview.js",
  "js/exporter.js",
  "js/ribbon.js",
  "js/animation.js",
  "js/app.js",
];

// Strip import/export and collect exported names.
export function transform(src) {
  const names = [];
  const aliases = []; // [exportedName, localName] for `export { local as exported }`
  let code = src;

  // import { a, b as c } from "..."  ->  const { a, b: c } = WF;
  code = code.replace(/^import\s*\{([^}]*)\}\s*from\s*["'][^"']+["'];?\s*$/gm, (m, ns) => `const { ${ns.trim()} } = WF;`);
  // import * as NS from "..." (unused in this codebase, handled defensively)
  code = code.replace(/^import\s*\*\s*as\s+(\w+)\s*from\s*["'][^"']+["'];?\s*$/gm, (m, n) => `const ${n} = WF;`);
  // import "..." side-effect (unused here)
  code = code.replace(/^import\s*["'][^"']+["'];?\s*$/gm, (m) => "");

  // export const/let/var NAME  ->  const/let/var NAME  (record NAME)
  code = code.replace(/^export\s+(const|let|var)\s+([A-Za-z_$][\w$]*)/gm, (m, kw, name) => {
    names.push(name);
    return `${kw} ${name}`;
  });
  // export function/class NAME -> function/class NAME
  code = code.replace(/^export\s+(function|class)\s+([A-Za-z_$][\w$]*)/gm, (m, kw, name) => {
    names.push(name);
    return `${kw} ${name}`;
  });
  // export { a, b as c };  ->  (record the exports, drop the statement).
  // Leaving this behind used to produce a bundle with a bare `export` in a classic
  // script, i.e. a SyntaxError that stopped the whole app from loading.
  code = code.replace(/^export\s*\{([^}]*)\}\s*;?\s*$/gm, (m, list) => {
    for (const part of list.split(",").map(s => s.trim()).filter(Boolean)) {
      const mm = /^([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?$/.exec(part);
      if (!mm) continue;
      if (mm[2]) aliases.push([mm[2], mm[1]]);
      else names.push(mm[1]);
    }
    return "";
  });
  // export default ... (unused here)
  code = code.replace(/^export\s+default\b/gm, () => "");

  return { code, names, aliases };
}

function buildCore() {
  const parts = [];
  for (const rel of MODULES) {
    const src = readFileSync(join(root, rel), "utf8");
    const { code, names, aliases } = transform(src);
    const pushes = names.map(n => `WF.${n} = ${n};`)
      .concat(aliases.map(([exported, local]) => `WF.${exported} = ${local};`))
      .join("\n");
    parts.push(`// ---- ${rel} ----\n(function(){\n'use strict';\n${code}\n${pushes}\n})();`);
  }
  return parts.join("\n\n");
}

// Fail the build loudly instead of shipping a bundle that cannot even parse.
function assertBundleIsClassicScript(code) {
  try {
    new Function(code);
  } catch (e) {
    throw new Error(`bundle is not a valid classic script: ${e.message}\n` +
      `（通常是某个源文件里用了 build.mjs 没处理掉的 export/import 形式）`);
  }
}

export function buildBundle() {
  const core = buildCore();
  const banner = "/* WebFacer bundle (generated by build.mjs — do not hand-edit) */\nvar WF = window.WF = window.WF || {};\n";
  const out = banner + "\n" + core + "\n";
  assertBundleIsClassicScript(out);
  return out;
}

const out = join(root, "js", "bundle.js");
writeFileSync(out, buildBundle(), "utf8");
console.log(`wrote ${out} (${MODULES.length} modules)`);
